# use an offical node.js runtime as a parent image
FROM node:22-alpine


#set the working directory in container

WORKDIR /app

# Copy the package.jsn and packae-lock json to the container
COPY package*